env: "dev"

http_server:
  address: "0.0.0.0"
  port: 8080

database:
  username: "postgres"
  password: "admin"
  host: "pr-db"
  port: "5432"
  db_name: "prservice"
  migrations_path: "./migrations"
